openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    Contacts API by Ozan Can CUYAR
tags:
  - name: contacts
    description: Operations about contacts
  - name: auth
    description: Authentication and user management
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-9tvm.onrender.com
paths:
  /auth/register:
    $ref: '../swagger/paths/auth/register.yaml'

  /auth/login:
    $ref: '../swagger/paths/auth/login.yaml'

  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    put:
      $ref: '../swagger/paths/contacts/{id}/put.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer